[tool.poetry]
name = "podkilla"
version = "0.1.0"
description = ""
authors = ["Gigi <the.gigi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.0"
sh = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
